# Generated by Django 4.2.8 on 2023-12-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_audios_audio_alter_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='audio',
            field=models.FileField(upload_to='myapp/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='myapp/'),
        ),
    ]
